name: Unit tests
on: [pull_request, workflow_call]

jobs:
  check-unit-tests:
    name: Check unit tests
    runs-on: ubuntu-latest
    container: python:3.11-alpine3.16

    services:
      database:
        image: postgres:14.6-alpine
        env:
          - POSTGRES_DB=dbname
          - POSTGRES_USER=dbuser
          - POSTGRES_PASSWORD=password

      redis:
        image: redis:7.0.5-alpine
        hostname: redis

    steps:
      - users: actions/checkout@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r /temp/requirements.txt

      - name: Run Test's
        env:
          - DB_HOST=database
          - DB_NAME=dbname
          - DB_USER=dbuser
          - DB_PASS=password

        run: |
          python /temp/manage.py test

